apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv-steady.yaml
  - pv-bursty.yaml
  - pv-trickle.yaml
  - pv-churn.yaml
  - pv-delayed.yaml
  - pvc-steady.yaml
  - pvc-bursty.yaml
  - pvc-trickle.yaml
  - pvc-churn.yaml
  - pvc-delayed.yaml
  - pod-steady.yaml
  - pod-bursty.yaml
  - pod-trickle.yaml
  - pod-churn.yaml
  - pod-delayed.yaml
