apiVersion: v1
kind: PersistentVolume
metadata:
  name: cpo-ci-bursty-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ci-hostpath
  hostPath:
    path: /var/lib/rancher/k3s/storage/cpo-ci-pv/cpo-ci-bursty-pvc
    type: Directory
