apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cpo-ci-bursty-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ci-hostpath
  volumeName: cpo-ci-bursty-pv
  resources:
    requests:
      storage: 500Mi
