//go:build !ignore_autogenerated

/*
Copyright 2024 pbsladek.

SPDX-License-Identifier: MIT
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnthropicProviderSpec) DeepCopyInto(out *AnthropicProviderSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnthropicProviderSpec.
func (in *AnthropicProviderSpec) DeepCopy() *AnthropicProviderSpec {
	if in == nil {
		return nil
	}
	out := new(AnthropicProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudgetSpec) DeepCopyInto(out *BudgetSpec) {
	*out = *in
	if in.NamespaceBudgets != nil {
		in, out := &in.NamespaceBudgets, &out.NamespaceBudgets
		*out = make([]NamespaceBudgetSpec, len(*in))
		copy(*out, *in)
	}
	if in.WorkloadBudgets != nil {
		in, out := &in.WorkloadBudgets, &out.WorkloadBudgets
		*out = make([]WorkloadBudgetSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudgetSpec.
func (in *BudgetSpec) DeepCopy() *BudgetSpec {
	if in == nil {
		return nil
	}
	out := new(BudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPlan) DeepCopyInto(out *CapacityPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPlan.
func (in *CapacityPlan) DeepCopy() *CapacityPlan {
	if in == nil {
		return nil
	}
	out := new(CapacityPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapacityPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPlanList) DeepCopyInto(out *CapacityPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CapacityPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPlanList.
func (in *CapacityPlanList) DeepCopy() *CapacityPlanList {
	if in == nil {
		return nil
	}
	out := new(CapacityPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapacityPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPlanNotification) DeepCopyInto(out *CapacityPlanNotification) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPlanNotification.
func (in *CapacityPlanNotification) DeepCopy() *CapacityPlanNotification {
	if in == nil {
		return nil
	}
	out := new(CapacityPlanNotification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapacityPlanNotification) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPlanNotificationList) DeepCopyInto(out *CapacityPlanNotificationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CapacityPlanNotification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPlanNotificationList.
func (in *CapacityPlanNotificationList) DeepCopy() *CapacityPlanNotificationList {
	if in == nil {
		return nil
	}
	out := new(CapacityPlanNotificationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CapacityPlanNotificationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPlanNotificationSpec) DeepCopyInto(out *CapacityPlanNotificationSpec) {
	*out = *in
	out.Cooldown = in.Cooldown
	out.Slack = in.Slack
	in.Email.DeepCopyInto(&out.Email)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPlanNotificationSpec.
func (in *CapacityPlanNotificationSpec) DeepCopy() *CapacityPlanNotificationSpec {
	if in == nil {
		return nil
	}
	out := new(CapacityPlanNotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPlanNotificationStatus) DeepCopyInto(out *CapacityPlanNotificationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSentTime != nil {
		in, out := &in.LastSentTime, &out.LastSentTime
		*out = (*in).DeepCopy()
	}
	if in.LastSentChannels != nil {
		in, out := &in.LastSentChannels, &out.LastSentChannels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPlanNotificationStatus.
func (in *CapacityPlanNotificationStatus) DeepCopy() *CapacityPlanNotificationStatus {
	if in == nil {
		return nil
	}
	out := new(CapacityPlanNotificationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPlanSpec) DeepCopyInto(out *CapacityPlanSpec) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ReconcileInterval = in.ReconcileInterval
	out.SampleInterval = in.SampleInterval
	out.Thresholds = in.Thresholds
	in.Budgets.DeepCopyInto(&out.Budgets)
	out.LLMInsightsInterval = in.LLMInsightsInterval
	in.LLM.DeepCopyInto(&out.LLM)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPlanSpec.
func (in *CapacityPlanSpec) DeepCopy() *CapacityPlanSpec {
	if in == nil {
		return nil
	}
	out := new(CapacityPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPlanStatus) DeepCopyInto(out *CapacityPlanStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PVCs != nil {
		in, out := &in.PVCs, &out.PVCs
		*out = make([]PVCSummary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Summary.DeepCopyInto(&out.Summary)
	if in.TopRisks != nil {
		in, out := &in.TopRisks, &out.TopRisks
		*out = make([]PVCRiskSummary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RiskChanges != nil {
		in, out := &in.RiskChanges, &out.RiskChanges
		*out = make([]PVCRiskChange, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NamespaceForecasts != nil {
		in, out := &in.NamespaceForecasts, &out.NamespaceForecasts
		*out = make([]StorageBudgetForecast, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WorkloadForecasts != nil {
		in, out := &in.WorkloadForecasts, &out.WorkloadForecasts
		*out = make([]StorageBudgetForecast, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Anomalies != nil {
		in, out := &in.Anomalies, &out.Anomalies
		*out = make([]PVCAnomaly, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPlanStatus.
func (in *CapacityPlanStatus) DeepCopy() *CapacityPlanStatus {
	if in == nil {
		return nil
	}
	out := new(CapacityPlanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPlanSummary) DeepCopyInto(out *CapacityPlanSummary) {
	*out = *in
	if in.TopByUsage != nil {
		in, out := &in.TopByUsage, &out.TopByUsage
		*out = make([]PVCSummaryBrief, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopBySoonestToFull != nil {
		in, out := &in.TopBySoonestToFull, &out.TopBySoonestToFull
		*out = make([]PVCSummaryBrief, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopByGrowth != nil {
		in, out := &in.TopByGrowth, &out.TopByGrowth
		*out = make([]PVCSummaryBrief, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPlanSummary.
func (in *CapacityPlanSummary) DeepCopy() *CapacityPlanSummary {
	if in == nil {
		return nil
	}
	out := new(CapacityPlanSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailNotificationSpec) DeepCopyInto(out *EmailNotificationSpec) {
	*out = *in
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailNotificationSpec.
func (in *EmailNotificationSpec) DeepCopy() *EmailNotificationSpec {
	if in == nil {
		return nil
	}
	out := new(EmailNotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FastAPIProviderSpec) DeepCopyInto(out *FastAPIProviderSpec) {
	*out = *in
	out.Cooldown = in.Cooldown
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FastAPIProviderSpec.
func (in *FastAPIProviderSpec) DeepCopy() *FastAPIProviderSpec {
	if in == nil {
		return nil
	}
	out := new(FastAPIProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMProviderSpec) DeepCopyInto(out *LLMProviderSpec) {
	*out = *in
	out.Timeout = in.Timeout
	if in.Temperature != nil {
		in, out := &in.Temperature, &out.Temperature
		*out = new(float64)
		**out = **in
	}
	out.OpenAI = in.OpenAI
	out.Anthropic = in.Anthropic
	out.FastAPI = in.FastAPI
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMProviderSpec.
func (in *LLMProviderSpec) DeepCopy() *LLMProviderSpec {
	if in == nil {
		return nil
	}
	out := new(LLMProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceBudgetSpec) DeepCopyInto(out *NamespaceBudgetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceBudgetSpec.
func (in *NamespaceBudgetSpec) DeepCopy() *NamespaceBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAIProviderSpec) DeepCopyInto(out *OpenAIProviderSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIProviderSpec.
func (in *OpenAIProviderSpec) DeepCopy() *OpenAIProviderSpec {
	if in == nil {
		return nil
	}
	out := new(OpenAIProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCAnomaly) DeepCopyInto(out *PVCAnomaly) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCAnomaly.
func (in *PVCAnomaly) DeepCopy() *PVCAnomaly {
	if in == nil {
		return nil
	}
	out := new(PVCAnomaly)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCRiskChange) DeepCopyInto(out *PVCRiskChange) {
	*out = *in
	if in.PreviousProjectedFullAt != nil {
		in, out := &in.PreviousProjectedFullAt, &out.PreviousProjectedFullAt
		*out = (*in).DeepCopy()
	}
	if in.CurrentProjectedFullAt != nil {
		in, out := &in.CurrentProjectedFullAt, &out.CurrentProjectedFullAt
		*out = (*in).DeepCopy()
	}
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCRiskChange.
func (in *PVCRiskChange) DeepCopy() *PVCRiskChange {
	if in == nil {
		return nil
	}
	out := new(PVCRiskChange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCRiskSummary) DeepCopyInto(out *PVCRiskSummary) {
	*out = *in
	if in.DaysUntilFull != nil {
		in, out := &in.DaysUntilFull, &out.DaysUntilFull
		*out = new(float64)
		**out = **in
	}
	if in.ProjectedFullAt != nil {
		in, out := &in.ProjectedFullAt, &out.ProjectedFullAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCRiskSummary.
func (in *PVCRiskSummary) DeepCopy() *PVCRiskSummary {
	if in == nil {
		return nil
	}
	out := new(PVCRiskSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCSummary) DeepCopyInto(out *PVCSummary) {
	*out = *in
	if in.DaysUntilFull != nil {
		in, out := &in.DaysUntilFull, &out.DaysUntilFull
		*out = new(float64)
		**out = **in
	}
	if in.LastSampleTime != nil {
		in, out := &in.LastSampleTime, &out.LastSampleTime
		*out = (*in).DeepCopy()
	}
	if in.LastLLMTime != nil {
		in, out := &in.LastLLMTime, &out.LastLLMTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCSummary.
func (in *PVCSummary) DeepCopy() *PVCSummary {
	if in == nil {
		return nil
	}
	out := new(PVCSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCSummaryBrief) DeepCopyInto(out *PVCSummaryBrief) {
	*out = *in
	if in.DaysUntilFull != nil {
		in, out := &in.DaysUntilFull, &out.DaysUntilFull
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCSummaryBrief.
func (in *PVCSummaryBrief) DeepCopy() *PVCSummaryBrief {
	if in == nil {
		return nil
	}
	out := new(PVCSummaryBrief)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Sample) DeepCopyInto(out *Sample) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Sample.
func (in *Sample) DeepCopy() *Sample {
	if in == nil {
		return nil
	}
	out := new(Sample)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Sample) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SampleList) DeepCopyInto(out *SampleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Sample, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SampleList.
func (in *SampleList) DeepCopy() *SampleList {
	if in == nil {
		return nil
	}
	out := new(SampleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SampleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SampleSpec) DeepCopyInto(out *SampleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SampleSpec.
func (in *SampleSpec) DeepCopy() *SampleSpec {
	if in == nil {
		return nil
	}
	out := new(SampleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SampleStatus) DeepCopyInto(out *SampleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SampleStatus.
func (in *SampleStatus) DeepCopy() *SampleStatus {
	if in == nil {
		return nil
	}
	out := new(SampleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackNotificationSpec) DeepCopyInto(out *SlackNotificationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackNotificationSpec.
func (in *SlackNotificationSpec) DeepCopy() *SlackNotificationSpec {
	if in == nil {
		return nil
	}
	out := new(SlackNotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBudgetForecast) DeepCopyInto(out *StorageBudgetForecast) {
	*out = *in
	if in.DaysUntilBreach != nil {
		in, out := &in.DaysUntilBreach, &out.DaysUntilBreach
		*out = new(float64)
		**out = **in
	}
	if in.ProjectedBreachAt != nil {
		in, out := &in.ProjectedBreachAt, &out.ProjectedBreachAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBudgetForecast.
func (in *StorageBudgetForecast) DeepCopy() *StorageBudgetForecast {
	if in == nil {
		return nil
	}
	out := new(StorageBudgetForecast)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdSpec) DeepCopyInto(out *ThresholdSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdSpec.
func (in *ThresholdSpec) DeepCopy() *ThresholdSpec {
	if in == nil {
		return nil
	}
	out := new(ThresholdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadBudgetSpec) DeepCopyInto(out *WorkloadBudgetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadBudgetSpec.
func (in *WorkloadBudgetSpec) DeepCopy() *WorkloadBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadBudgetSpec)
	in.DeepCopyInto(out)
	return out
}
