apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: controller-manager-metrics-monitor
  labels:
    app.kubernetes.io/name: k8s-operator
    app.kubernetes.io/managed-by: kustomize
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-operator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
