---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - persistentvolumeclaims
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - capacityplanning.pbsladek.io
  resources:
  - capacityplannotifications
  - capacityplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capacityplanning.pbsladek.io
  resources:
  - capacityplannotifications/finalizers
  - capacityplans/finalizers
  verbs:
  - update
- apiGroups:
  - capacityplanning.pbsladek.io
  resources:
  - capacityplannotifications/status
  - capacityplans/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tutorial.example.com
  resources:
  - samples
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tutorial.example.com
  resources:
  - samples/finalizers
  verbs:
  - update
- apiGroups:
  - tutorial.example.com
  resources:
  - samples/status
  verbs:
  - get
  - patch
  - update
