apiVersion: v1
kind: Secret
metadata:
  name: capacityplan-smtp
  namespace: default
type: Opaque
stringData:
  host: "smtp.example.com"
  port: "587"
  username: "capacity-plan@example.com"
  password: "change-me"
